name: CI - Next.js Frontend

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Remove package-lock.json if exists
        run: |
          if [ -f package-lock.json ]; then
            rm package-lock.json
            echo "Removed package-lock.json to avoid conflicts with yarn.lock"
          fi

      - name: Set Yarn registry to Yarn mirror
        run: yarn config set registry https://registry.yarnpkg.com

      - name: Clean Yarn cache
        run: yarn cache clean

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Build project
        run: yarn build
